### ISSUE TITLE
Installation instructions are missing

### ISSUE THREAD

**Issue by kottkrig** [Jegp/elm-storage#1]
I could not find `elm-storage` in the Elm Package Repository and there are no instructions in the Readme on how I would go about installing this package in my project. 

Is my best bet to download the release and use it in my project?

**Comment by Jegp** [comment]
The maintainers are working on a new (and, I have to admit, better) way of working with browser storage: https://github.com/elm-lang/persistent-cache. And since the maintainers don't allow publishing of native code to the packages, we'll just have to wait until their own version is released. That was just a quick explanation on why it's not in the package repository.

In the meantime I think the easiest way is to pull the repository and import it directly in your code. I'll update the readme with installation instructions.
Thanks for pointing it out! :-)

**Comment by Jegp** [comment]
Closed by https://github.com/Jegp/elm-storage/commit/e2c64e07f6f65c1a1099e0aa60651c3d4825a74e
